name: BlazinJoin
main: iiFlamiinBlaze\BlazinJoin\BlazinJoin
description: An advanced join enhancement plugin!
version: 1.1.3
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPH9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: iiFlamiinBlaze
load: POSTWORLD
commands:
 blazinjoin:
  description: BlazinJoin command which allows you to edit the config easily
  permission: blazinjoin.command
permissions:
 blazinjoin.command:
  default: op